### ISSUE TITLE
Extract out platforms and url test page(s)

### ISSUE THREAD

**Issue by m-mujica** [bitovi/test-saucelabs#1]
```javascript
// test/saucelabs.js
var testSaucelabs = require("test-saucelabs");

testSaucelabs({
  url: "http://localhost:3000/test/test.html?hidepassed",
  platforms: [{
    browserName: 'firefox',
    platform: 'Windows 10',
    version: '50.0'
  }, {
    browserName: 'firefox',
    platform: 'OS X 10.11',
    version: '50.0'
  }]
});
```

In Steal we open multiple tests pages, so `url` might be an array but I could probably open a different issue for that. Steal also does not use the same platforms for all test pages, so I'm wondering if the `url` array could provide its own `platforms` array and default to the top platforms if undefined. 

```javascript
// test/saucelabs.js
var testSaucelabs = require("test-saucelabs");

testSaucelabs({
  url: [{
    url: "http://localhost:3000/test/test.html?hidepassed"
  }, {
    url: "http://localhost:3000/test/foo.html?hidepassed",
    platforms: [{
      browserName: 'firefox',
      platform: 'Windows 10',
      version: '50.0'
    }]
  }],
  platforms: [{
    browserName: 'firefox',
    platform: 'Windows 10',
    version: '50.0'
  }, {
    browserName: 'firefox',
    platform: 'OS X 10.11',
    version: '50.0'
  }]
});
```
@phillipskevin mentioned having a json config, too. Thoughts? @matthewp

**Comment by m-mujica** [comment]
https://github.com/stealjs/steal/blob/c6e7629bef50eddece3cbb6ab0f58505c0633fa1/test/test-sauce-labs.js#L96-L120

**Comment by matthewp** [comment]
I think this looks fine for the initial release. I wouldn't do a json config yet. Not that it wouldn't be nice, but if you add that then you problem need a corresponding cli utility. I'd stick with the JS api for now.
